# Действия с массивами

In [2]:
#Изменение формы массива

# Созданим одномерный массив
import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

# первое число задало число строк, а второе — число столбцов.
arr.shape = (2, 4) 
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

#Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])

'''У функции reshape есть дополнительный именованный аргумент order. 
Он задаёт принцип, по которому элементы заполняют массив новой формы. Если order='C' (по умолчанию), 
массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:'''

arr = np.arange(8)
arr_new_f = arr.reshape((2, 4), order='F')
arr_new_f
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
# транспонирование
'''Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование. 
Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.'''

# При транспонировании одномерного массива его форма не меняется:

arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# Индексы и срезы в массивах

In [3]:
'''Работа с одномерным массивом'''
# Созданим массив
arr = np.linspace(1, 2, 6)
arr
print(arr)
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

# Обратиться к его элементу по индексу можно так же, как и к списку:
print(arr[2])

# Привычная запись для срезов работает и для одномерных массивов:
print(arr[2:4])

# Revers massive
print(arr[::-1])

[1.  1.2 1.4 1.6 1.8 2. ]
1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


In [6]:
# Работа с многомерными массивами

#Создадим двумерный массив из одномерного:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
print(nd_array)
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])

nd_array[1, 2] # получили со второй строки, третьего столбца - отчет идет от 0 не забывай.
print(nd_array)

# Срез - первый символ колличество строк, второй какие данные по нумерации взять
nd_array[:2, 2]
# array([1., 3.])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


array([1., 3.])

# Practic

In [ ]:
# Введите свое решение ниже
import numpy as np

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
import numpy as np

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]
# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]
# В переменную line_4 сохраните строку 4
line_4 = mystery[3]
# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]
# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
part = mystery[1:4, 2:5]
# Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[::-1, -1] # or [:, -1][::-1]
# Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()



