# Векторы в NumPy и арифметика

In [2]:
'''В программировании вектором называют одномерный проиндексированный набор данных, другими словами — одномерный массив.'''

'''Операция, применённая к двум векторам, на самом деле применяется поэлементно. То есть при сложении двух векторов первым элементом 
нового вектора будет сумма первых элементов исходных векторов, вторым — сумма вторых элементов и т. д.'''

import numpy as np

# Умножение и возведение в степень
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

# Сравнение
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 > vec2
# array([False, False,  True, False])
vec = np.array([14,15,9,26,53,5,89])
vec <= 26
# array([ True,  True,  True,  True, False,  True, False])


array([ True,  True,  True,  True, False,  True, False])

# Продвинутые операции с векторами

In [7]:
'''Длина вектора, то есть расстояние между его началом и концом, [в евклидовом пространстве] вычисляется как квадратный 
корень из суммы квадратов всех его координат.'''
length = np.sqrt(np.sum(vec ** 2))
print(length)
# 5.0
# Для вычисления длины вектора нам потребуется функция norm:
length = np.linalg.norm(vec)
print(length)
# 5.0


'''Расстояние между двумя векторами, то есть расстояние между их концами, [в евклидовом пространстве] вычисляется как квадратный 
корень из суммы квадратов разностей соответствующих координат'''
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance
# 12.206555615733702
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance
# 12.206555615733702


'''Cкалярным произведением двух векторов называют сумму произведений их соответствующих координат. '''
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product
# 250.0
scalar_product = np.dot(vec1, vec2)
scalar_product
# 250.0

'''равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:'''

x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)
# 0

39.57271787481876
39.57271787481876


0

# Базовые статистические функции для векторов

In [6]:
# Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. 
# Их можно записывать как в виде np.min(<vector>) так и в виде <vector>.min()

vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
# 1
np.max(vec)
# 28

#Функция  mean
print(vec.mean()) 
#позволяет посчитать среднее значени



10.75
