In [8]:
'''Напишите функцию get_chess(a), которая принимает на вход длину стороны квадрата a и 
возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем 
углу всегда должен быть ноль.

Примечание. воспользуйтесь функцией np.zeros, а затем с помощью срезов без циклов задайте необходимым 
элементам значение 1.

В Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно 
применить этот принцип к двумерному массиву.'''

import numpy as np

def get_chess(a):
    arr = np.zeros((a,a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

a = 12
print(get_chess(a))

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [10]:

'''Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет 
доступна функция перемешивания плейлиста. Пользователю может настолько понравиться 
перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите 
хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым 
он был сгенерирован.

Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, 
генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает 
кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а 
также seed, с которым этот массив был получен.'''

import numpy as np

def shuffle_seed(array):
# Генерируем случайный seed в допустимом диапазоне
    seed = np.random.randint(2 ** 32)
    #Создаем псевдо  случайное число
    np.random.seed(seed)
    # Создаем копию массива, чтобы не изменять исходный
    result = np.random.permutation(array)
    return result, seed

array = [1, 2, 3, 4, 5]
print(shuffle_seed(array))

(array([5, 1, 2, 4, 3]), 792650723)


In [ ]:
'''Напишите функцию min_max_dist(*vectors), которая принимает на вход неограниченное число 
векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.'''

import numpy as np

def mix_max_dist(*vectors):
    distance = list() # Создаем список из которого потом выберем макс и мин
    for elem1 in range(len(vectors)): # Создаем последовательность векторов для дальнейшего вычисления
        for elem2 in range(elem1+1, len(vectors)): # цикл перебора как выше но +1 к старту
            distance.append(np.linalg.norm(vectors[elem1] - vectors[elem2])) # Добавили полученные результаты по вычеслению длинн межжду векторами 
    return min(distance), max(distance) # Вчислили макс и мин значение из списка

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

print(mix_max_dist(vec1, vec2, vec3))
# (5.196152422706632, 10.392304845413264)

(5.196152422706632, 10.392304845413264)


In [16]:
'''Напишите функцию any_normal, которая принимает на вход неограниченное число векторов 
через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

Пример'''

import numpy as np
def any_normal(*vectors):
    # Внешний цикл: перебираем все векторы по порядку
    for i in range(len(vectors)):
        # Внутренний цикл: перебираем все векторы, которые идут ПОСЛЕ текущего (i)
        # Это нужно, чтобы избежать повторных проверок одних и тех же пар
        for j in range(i+1, len(vectors)):
            # Проверяем перпендикулярность через скалярное произведение:
            # если скалярное произведение равно 0 - векторы перпендикулярны
            if np.dot(vectors[i], vectors[j]) == 0:
                # Нашли перпендикулярную пару - можно сразу вернуть True
                return True
    
    # Если дошли до этой точки - перпендикулярных пар не найдено
    return False

vec1 = np.array([2, 1])
vec2 = np.array([2, 1])
vec3 = np.array([2, 1])
print(any_normal(vec1, vec2, vec3))

False


In [1]:
'''Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 
(включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

Пример'''


import numpy as np
def get_loto(num):
    loto = np.random.randint(1,101, size=(num,  5, 5))
    return loto

get_loto(3)

array([[[ 1, 38, 93, 76, 40],
        [ 2, 40, 75,  6, 65],
        [44,  7, 50, 51, 56],
        [73, 46, 91, 36, 10],
        [27, 98, 46, 57, 37]],

       [[75, 10, 82,  1, 69],
        [50, 52, 24, 52, 52],
        [53, 57, 54, 86,  5],
        [60, 51,  6, 96, 11],
        [98, 44, 81, 20, 27]],

       [[99, 37, 97, 42, 59],
        [66, 56, 42, 65, 31],
        [16, 40, 18, 46, 77],
        [94, 30, 80, 78, 70],
        [68, 90, 32, 10, 18]]])

In [ ]:
'''апишите функцию get_unique_loto(num). Она так же, как и функция в задании 49.9.10, 
генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.'''

#My answer
import numpy as np
def get_unique_loto(num):
    
    loto_uniq = np.zeros((num, 5, 5), dtype = int)
    for i in range(num):
        choice = np.random.choice(np.arange(1, 101), size=(5, 5), replace=False)
        loto_uniq[i] = choice.reshape(5, 5)
    return loto_uniq

# SkillFactory answer
import numpy as np
def get_unique_loto(num):
    # 1. Создаём массив чисел от 1 до 100
    sample = np.arange(1, 101)
    
    # 2. Создаём пустой список для хранения результатов
    res = list()
    
    # 3. Генерируем нужное количество билетов (num раз)
    for i in range(num):
        # 4. Для каждого билета выбираем 25 уникальных чисел из sample
        #    и сразу формируем матрицу 5x5
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    
    # 5. Преобразуем список в numpy-массив
    res = np.array(res)
    
    # 6. Возвращаем результат
    return res
