Случайное число — это число, которое возникает в результате случайного процесса.

Псевдослучайные числа — это такая последовательность чисел, которая возникает с помощью применения математических формул к какому-то исходному числу (например, текущему времени в микросекундах). Элементы, получаемые таким образом, почти не зависят друг от друга: например, при генерации следующего 0 или 1 не имеет значения, что выпало ранее — 0 или 1.

# Случайные числа в NumPy

## Генерация float

In [ ]:
import numpy as np
np.random.rand()
# 0.06600758835806675

# Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:
np.random.rand() * 100
# 69.76076924077643

#На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов 
#через запятую целые числа, которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:
np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])

#Массив из двух случайных строк и трёх столбцов:
np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

# Если передать в rand кортеж, возникнет ошибка:
shape = (3, 4)
np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer
# Ошибка типов: кортеж не может быть интерпретирован как целое число.

#Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:
shape = (3, 4)
np.random.rand(*shape)
# array([[0.66169176, 0.19455777, 0.06451088, 0.31919608],
#        [0.73536951, 0.67104408, 0.4762727 , 0.88153576],
#        [0.70672971, 0.96677145, 0.09273995, 0.86356465]])

# Это можно сделать без распоковки с помощью sample
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

#Не всегда требуются числа в диапазоне именно от 0 до 1. На самом деле с помощью специальных формул можно из 
# диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — в
# NumPy доступна функция uniform:
uniform(low=0.0, high=1.0, size=None)
# Первые два аргумента — нижняя и верхняя границы диапазона в формате float, 
# третий опциональный аргумент — форма массива (если не задан, возвращается одно число). Форма массива задаётся кортежем или одним числом.

# Пример
np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])
np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])



array([[0.80171658, 0.09645023, 0.35894768],
       [0.73742012, 0.08855669, 0.33173645]])

## Генерация int