Случайное число — это число, которое возникает в результате случайного процесса.

Псевдослучайные числа — это такая последовательность чисел, которая возникает с помощью применения математических формул к какому-то исходному числу (например, текущему времени в микросекундах). Элементы, получаемые таким образом, почти не зависят друг от друга: например, при генерации следующего 0 или 1 не имеет значения, что выпало ранее — 0 или 1.

# Случайные числа в NumPy

## Генерация float

In [2]:
import numpy as np
np.random.rand()
# 0.06600758835806675

# Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:
np.random.rand() * 100
# 69.76076924077643

#На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов 
#через запятую целые числа, которые задают форму генерируемого массива. Например, получим массив из пяти случайных чисел:
np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])

#Массив из двух случайных строк и трёх столбцов:
np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

# Если передать в rand кортеж, возникнет ошибка:
shape = (3, 4)
np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer
# Ошибка типов: кортеж не может быть интерпретирован как целое число.

#Конечно, можно было бы распаковать кортеж, чтобы избавиться от ошибки:
shape = (3, 4)
np.random.rand(*shape)
# array([[0.66169176, 0.19455777, 0.06451088, 0.31919608],
#        [0.73536951, 0.67104408, 0.4762727 , 0.88153576],
#        [0.70672971, 0.96677145, 0.09273995, 0.86356465]])

# Это можно сделать без распоковки с помощью sample
shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],
#       [0.82195372, 0.26435273, 0.00957881]])

#Не всегда требуются числа в диапазоне именно от 0 до 1. На самом деле с помощью специальных формул можно из 
# диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — в
# NumPy доступна функция uniform:
uniform(low=0.0, high=1.0, size=None)
# Первые два аргумента — нижняя и верхняя границы диапазона в формате float, 
# третий опциональный аргумент — форма массива (если не задан, возвращается одно число). Форма массива задаётся кортежем или одним числом.

# Пример
np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])
np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])



TypeError: 'tuple' object cannot be interpreted as an integer

## Генерация int

In [ ]:
# Для генерации целых чисел используется функция random.randint:
# randint(low, high=None, size=None, dtype=int)
'''Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.
Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.
Сгенерируем таблицу 2x3 от 0 до 3 включительно:
'''

np.random.randint(4, size=(2,3))
# array([[3, 0, 1],
#       [2, 1, 3]])

#Чтобы задать и нижнюю, и верхнюю границы самостоятельно, передадим два числа, а затем форму:

np.random.randint(6, 12, size=(3,3))
# array([[ 9,  6, 10],
#        [10, 11, 10],
#        [ 7, 10, 11]])


# Генерация выборок

In [ ]:
# Просто перемешать все числа в массиве позволяет функция random.shuffle.
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

#Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. 
# Она принимает на вход один аргумент — или массив целиком, или одно число:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


np.random.permutation(n)
# еремешать набор чисел от 0 до n-1 можно с помощью записи, где n — верхняя граница, 
# которая бы использовалась для генерации набора чисел функцией arange.


# Чтобы получить случайный набор объектов из массива, используется функция random.choice:
choice(a, size=None, replace=True)
'''a — одномерный массив или число для генерации arange(a);
size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).'''



In [5]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Ivan' 'Maria']


# Seed генератора псевдослучайных чисел

In [9]:
# Самостоятельно задать seed в NumPy можно с помощью функции np.random.seed(<np.uint32>)
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [16]:
#Если вы запустите этот код на своём компьютере, то, скорее всего, увидите тот же самый набор чисел!
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]
'''При этом запуск одной и той же функции генерации случайных чисел несколько  
раз после задания seed не приводит к генерации одних и тех же чисел. Однако итоговый результат 
работы всегда будет одинаковый в совокупности.
'''

[8 8 3]
[7 7 0]
[4 2 5]


'При этом запуск одной и той же функции генерации случайных чисел несколько  \nраз после задания seed не приводит к генерации одних и тех же чисел. Однако итоговый результат \nработы всегда будет одинаковый в совокупности.\n'