# Типы данных

In [ ]:
import numpy as np

'''Это тип данных с общим корнем int. Int может быть со следующими окончаниями: int8, int16, int32 и int64. 
Окончание типа данных в NumPy показывает, сколько битов памяти должно быть выделено для хранения переменной.'''

np.int8()  #  Преобразование обычного числа int в Numpy 
np.float() #  Преобразование обычного числа float в Numpy 
np.finfo(np.float16) or np.iinfo(np.int8()) # ПРоверка границ

'''
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
np.finfo(np.float64)

Resolution (от англ. «разрешение») в выводе finfo означает точность, с которой сохраняется десятичная часть 
числа в стандартном виде. Для float16 это 0.001, то есть числа 4.12 и 4.13 будут отличимы друг от друга, а вот 4.124 и 4.125 — нет. 
Третий знак числа float16 идёт уже с шагом 0.005:

print(np.float16(4.12))
# 4.12
print(np.float16(4.13))
# 4.13
print(np.float16(4.123))
# 4.12
print(np.float16(4.124))
# 4.125
print(np.float16(4.125))
# 4.125
''' 

In [ ]:
# Дополнительные типы данных в NumPy

print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

'''Следует обратить внимание на типы данных bool_ и str_. Они аналогичны bool и str из встроенных в Python'''


In [28]:
import numpy as np

b = np.uint(124)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)
# iinfo(min=0, max=255, dtype=uint8)
np.finfo(np.float128)

124
<class 'numpy.uint64'>


finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

In [21]:
result = np.uint8(-456)
print(result)

56


/tmp/ipykernel_4297/3739570326.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  result = np.uint8(-456)


# Массивы в Numpy

In [ ]:
'''
np.array # Создать массив arr = np.array([1,5,2,9,10])

dtype # Задать тип данных arr = np.array([1,5,2,9,10], dtype=np.int8)

.ndim # Узнать размерность массива можно с помощью arr.ndim
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)
arr.ndim
# 1
nd_arr.ndim
# 2               

.size # Узнать общее число элементов в массиве можно с помощью arr.size

.shape # Форма или структура массива хранится в атрибуте  arr.shape Форма массива определяется от длины внешнего массива (3) к внутреннему (3)


arr.itemsize # Узнать, сколько «весит» каждый элемент массива в байтах позволяет 
arr.itemsize
# 1
nd_arr.itemsize
# 2
Действительно, в arr хранятся числа в виде int8 (8 бит => 1 байт), а в nd_arr — в виде int16 (16 бит => 2 байта).

'''

# Заполнение новых массивов

'''
np.zeros - Массив из нулей создаётся функцией
Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж) 
и dtype (необязательный) — тип данных, который будет храниться в массиве.

Создадим одномерный массив из пяти элементов:

zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])
Создадим трёхмерный массив с формой 5x4x3 и типом float32:

zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)
'''


'''
arange - создание одномерных массивов
arange([start,] stop, [step,], dtype=None)

Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:

start (входит в диапазон возвращаемых значений) задаёт начальное число;
stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
step задаёт шаг, с которым в массив добавляются новые значения.
'''

'''
linspace -- функция возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
endpoint — включён или исключён конец диапазона (по умолчанию включён);
retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

Давайте потренируемся. Создадим массив из десяти чисел между 1 и 2:
arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

Создадим массив из десяти чисел между 1 и 2, не включая 2:
arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1

'''

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr.dtype # Тип данных в массиве

dtype('int8')

In [47]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float128)
print(arr)

[ 3.4523400e+05  8.7636212e+05  0.0000000e+00 -1.0000000e+03
  9.9999999e+07]


In [ ]:
import numpy as np
# Свойства NumPy-массивов
# Узнать размерность массива  .ndim
# Узнать общее число элементов в массиве можно с помощью .size

arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

print(arr.ndim)
# 1
nd_arr.ndim
# 2

1


2

In [16]:
import numpy as np
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)


0.45
